language: scala
scala:
- 2.12.1
jdk:
- oraclejdk8
env:
  global:
  - secure: kmmRJcAohvq+bTHtEorppUkDo9uTOSovzphboGZjX+VF6Z0Wf2n+hAzWjFM3AgQ6y0JoMMes3ITGmU6lIpU5Kca5l+vEm1lS8HHIQbckXo277NRghrAz7tFQ0AvZ+7edoeR74Fx9xRGElUic1WO+gyhy9VJBwe4mPDYmpSvUt3120sbsumpidWl3D5qQZpBZvCe8364/d6gZVc2Mp22rpZ+z6GP/sD0oq6Of7VQbBM5bkBq+s7VtEZNRUidYotk24a5F2vmP1laJQtTq5NlA82HTzWbW2wZt1ip2z9V+QsBA5D2RBPe2IRKjfbLOAFMLMoItm1ttf08kAZR6nLd7MfuopBSuSoozVxFMd1JRaBgS5W6lof04RCiGJQS139UmjTxpykdTO2Ihf4RcfLrNlKBTLnV5TZW87ekRfSTH/+Ja4DkWFtmdDYPxBbl0S6GrsBfOxHW1avGEfjPtICBMeda1n6GS+RFSAYHBxzQ3nK8rput99kvVyqNWRbbHL+atL2rKLUGblSwkV9YmIuKbFMbNiNUQRS5fQWMDLU8V3BXRp0JmKrH8TTf6ycQt/XorDwFbHBOJ9VEgHTWb4X0/3jlRb92vM/EqU+Ifc5jU3Yny30PAwsMon3oXH4PMkFaSdoiSE03Z1eiQ1I+5QM+2bFGw+LDKYbFMtKOIsVq1PhI=
  - secure: baNNqvoVu0ya7RuQiWQ5g1Zf5u12QyNC89bWpFz4a8go1pkCML3JdF192rALMFnvZMaVJ3FYNpL1pE1e3CY4x9w0z9zdXStVnHa2vPYgwVJyNPGX8NdHfBJsPQXH88DP9SjDXhjOqj3Ms2RcAkKSN+QPTIuHhfX2xiNwcmaK4+VZhlAxngu4Rzz4prjGWolJVPP09vO5QrqT5KJxdeV58eA7rCkRzS0OhSgbwRrq3Ow4Z1eA56q0djAo4VoTUGDBuW/TH8a6VLU0MHx04vIGdrUpAJVmwGTnjpPm5UsEb5upIyrNT3ZGp/a1S1IJzAlhEGq3hSHHBYNVPw1DU5L88LQZ6+IGGAn2fuAGhT4WfQnnBIlIvNmo+GWQ/TpuhhU88uzSyfZX78HZoe9pG+vJXqAJnhdZf7q6CEuUFSsXi19sC7Njn/lP3HW/H4msOAnLgiYVu1+UsvRmxdZCc+6KoAnpMKdbWYWAjesFeJ+AK7/G6l0IO4A3zUAgV8Hvx/OJNcf0gddarMcJf+I+UE2rM11XfM5x4OSmgNMm52bTkqnFtk7gt81R5vZ0pFH4ukzfspgSMrFClBsTvQlaZafw9Qf5x8rGOfu36cEJ4LiNFtH9k9JSgCnpvZ8El9L5xi/ZRbVjOHhU2W9Llm1VD6JFWDVjZ4XpXHq/7FbdbCnUlm4=
after_success:
  - >
      env | grep -v SONATYPE &&
      test "${TRAVIS_PULL_REQUEST}" = 'false' &&
      test "${TRAVIS_BRANCH}" = 'master' &&
      sbt 'set credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", System.getenv("SONATYPE_USER"), System.getenv("SONATYPE_PASS"))' "release with-defaults"
