language: scala
scala:
- 2.11.8
- 2.12.1
jdk:
- oraclejdk8
env:
  global:
  - secure: kmmRJcAohvq+bTHtEorppUkDo9uTOSovzphboGZjX+VF6Z0Wf2n+hAzWjFM3AgQ6y0JoMMes3ITGmU6lIpU5Kca5l+vEm1lS8HHIQbckXo277NRghrAz7tFQ0AvZ+7edoeR74Fx9xRGElUic1WO+gyhy9VJBwe4mPDYmpSvUt3120sbsumpidWl3D5qQZpBZvCe8364/d6gZVc2Mp22rpZ+z6GP/sD0oq6Of7VQbBM5bkBq+s7VtEZNRUidYotk24a5F2vmP1laJQtTq5NlA82HTzWbW2wZt1ip2z9V+QsBA5D2RBPe2IRKjfbLOAFMLMoItm1ttf08kAZR6nLd7MfuopBSuSoozVxFMd1JRaBgS5W6lof04RCiGJQS139UmjTxpykdTO2Ihf4RcfLrNlKBTLnV5TZW87ekRfSTH/+Ja4DkWFtmdDYPxBbl0S6GrsBfOxHW1avGEfjPtICBMeda1n6GS+RFSAYHBxzQ3nK8rput99kvVyqNWRbbHL+atL2rKLUGblSwkV9YmIuKbFMbNiNUQRS5fQWMDLU8V3BXRp0JmKrH8TTf6ycQt/XorDwFbHBOJ9VEgHTWb4X0/3jlRb92vM/EqU+Ifc5jU3Yny30PAwsMon3oXH4PMkFaSdoiSE03Z1eiQ1I+5QM+2bFGw+LDKYbFMtKOIsVq1PhI=
  - secure: HyXJiSHmuu1pb1inZ0AYwouJvd3k0GOCKQG/wxsesSGrbhZpQd6Jp4ruGr5CTluNlmD3HvMx/IMv7U+OHoxIamSsDHbDArxKWvA2JyxXyNvEX8iDp0ojSOnIq4X7SlCJ7JukC5+0WyKs/wejtxk68Njzp4ytUWUCNmtZV08DlCeNCgRxQnd6vzeceedQuD0LR+XnjOVf3YQjxEZvhwuACWQRDpOrbfvQXPZz2bZ7FwkgCMwJHL/EwriXFb7RqiCXwXdVoFX9Fy4q4W8Mh4+JblB5O6u9rgnrKRGjXU9IMLPtnFHODhxabaTbjjpu/r+UiiJGdToE3g9ASOcqFHW2Rb8EzyjQ5bXXN/6a74pSTAexnSfy4t/Nh98cIGncvwnQWofmNCsweeirRZyAE/qQ1fcSbR0HAqoxderivtaOpBP0jvmNozy3p93tpp7fyH2slj+2z3Uw8y3pkTolFFhfKyV2MXOOCx5Mp9sLd5d4MDZC9itmW+nWTIE0NVC5DxXIlMUbHFj9NkVWBUHEJr+xZruv9aiWmXpW3IlSpLu3KL6DUkATx8eUyO/k/Vq7HOlZzSp144wAnJaUHMTmS0ttA7ye2LpA6S/XwQeHIVdPxFCSCpGpWSG4Lziqg/KkxXJsixBN4q0zjIs3/wNOdFb0/3FA+FT4Lx7L7AqFfrz42uE=
after_success:
  - >
      test "${TRAVIS_PULL_REQUEST}" = 'false' &&
      test "${TRAVIS_JDK_VERSION}" = 'oraclejdk8' &&
      sbt 'set credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", System.getenv("SONATYPE_USER"), System.getenv("SONATYPE_PASS"))' "release with-defaults"
